CREATE TABLE IF NOT EXISTS `temp_language` (
  `3letter` char(3) NOT NULL COMMENT 'ISO 639-2 Code',
  `2letter` varchar(2) DEFAULT NULL COMMENT 'ISO 639-1 Code',
  `native` varchar(255) DEFAULT NULL,
  `n_EN` varchar(255) DEFAULT NULL,
  `n_FR` varchar(255) DEFAULT NULL,
  `n_CA` varchar(255) DEFAULT NULL,
  `n_DE` varchar(255) DEFAULT NULL,
  `n_ES` varchar(255) DEFAULT NULL,
  `n_NL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`3letter`),
  KEY `2letter` (`2letter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Gegevens worden uitgevoerd voor tabel `temp_language`
--

INSERT INTO `temp_language` (`3letter`, `2letter`, `native`, `n_EN`, `n_FR`, `n_CA`, `n_DE`, `n_ES`, `n_NL`) VALUES
('aar', 'aa', 'Afaraf', 'Afar', 'afar', NULL, NULL, NULL, NULL),
('abk', 'ab', 'аҧсуа бызшәа, аҧсшәа', 'Abkhazian', 'abkhaze', NULL, NULL, NULL, NULL),
('ace', NULL, NULL, 'Achinese', 'aceh', NULL, NULL, NULL, NULL),
('ach', NULL, NULL, 'Acoli', 'acoli', NULL, NULL, NULL, NULL),
('ada', NULL, NULL, 'Adangme', 'adangme', NULL, NULL, NULL, NULL),
('ady', NULL, NULL, 'Adyghe; Adygei', 'adyghé', NULL, NULL, NULL, NULL),
('afa', NULL, NULL, 'Afro-Asiatic languages', 'afro-asiatiques, langues', NULL, NULL, NULL, NULL),
('afh', NULL, NULL, 'Afrihili', 'afrihili', NULL, NULL, NULL, NULL),
('afr', 'af', 'Afrikaans', 'Afrikaans', 'afrikaans', NULL, NULL, NULL, NULL),
('ain', NULL, NULL, 'Ainu', 'aïnou', NULL, NULL, NULL, NULL),
('aka', 'ak', 'Akan', 'Akan', 'akan', NULL, NULL, NULL, NULL),
('akk', NULL, NULL, 'Akkadian', 'akkadien', NULL, NULL, NULL, NULL),
('alb', 'sq', 'gjuha shqipe', 'Albanian', 'albanais', NULL, NULL, NULL, NULL),
('ale', NULL, NULL, 'Aleut', 'aléoute', NULL, NULL, NULL, NULL),
('alg', NULL, NULL, 'Algonquian languages', 'algonquines, langues', NULL, NULL, NULL, NULL),
('alt', NULL, NULL, 'Southern Altai', 'altai du Sud', NULL, NULL, NULL, NULL),
('amh', 'am', 'አማርኛ', 'Amharic', 'amharique', NULL, NULL, NULL, NULL),
('ang', NULL, NULL, 'English, Old (ca.450-1100)', 'anglo-saxon (ca.450-1100)', NULL, NULL, NULL, NULL),
('anp', NULL, NULL, 'Angika', 'angika', NULL, NULL, NULL, NULL),
('apa', NULL, NULL, 'Apache languages', 'apaches, langues', NULL, NULL, NULL, NULL),
('ara', 'ar', 'العربية', 'Arabic', 'arabe', NULL, NULL, NULL, NULL),
('arc', NULL, NULL, 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)', 'araméen d''empire (700-300 BCE)', NULL, NULL, NULL, NULL),
('arg', 'an', 'aragonés', 'Aragonese', 'aragonais', NULL, NULL, NULL, NULL),
('arm', 'hy', 'Հայերեն', 'Armenian', 'arménien', NULL, NULL, NULL, NULL),
('arn', NULL, NULL, 'Mapudungun; Mapuche', 'mapudungun; mapuche; mapuce', NULL, NULL, NULL, NULL),
('arp', NULL, NULL, 'Arapaho', 'arapaho', NULL, NULL, NULL, NULL),
('art', NULL, NULL, 'Artificial languages', 'artificielles, langues', NULL, NULL, NULL, NULL),
('arw', NULL, NULL, 'Arawak', 'arawak', NULL, NULL, NULL, NULL),
('asm', 'as', 'অসমীয়া', 'Assamese', 'assamais', NULL, NULL, NULL, NULL),
('ast', NULL, NULL, 'Asturian; Bable; Leonese; Asturleonese', 'asturien; bable; léonais; asturoléonais', NULL, NULL, NULL, NULL),
('ath', NULL, NULL, 'Athapascan languages', 'athapascanes, langues', NULL, NULL, NULL, NULL),
('aus', NULL, NULL, 'Australian languages', 'australiennes, langues', NULL, NULL, NULL, NULL),
('ava', 'av', 'авар мацӀ, магӀарул мацӀ', 'Avaric', 'avar', NULL, NULL, NULL, NULL),
('ave', 'ae', 'avesta', 'Avestan', 'avestique', NULL, NULL, NULL, NULL),
('awa', NULL, NULL, 'Awadhi', 'awadhi', NULL, NULL, NULL, NULL),
('aym', 'ay', 'aymar aru', 'Aymara', 'aymara', NULL, NULL, NULL, NULL),
('aze', 'az', 'azərbaycan dili', 'Azerbaijani', 'azéri', NULL, NULL, NULL, NULL),
('bad', NULL, NULL, 'Banda languages', 'banda, langues', NULL, NULL, NULL, NULL),
('bai', NULL, NULL, 'Bamileke languages', 'bamiléké, langues', NULL, NULL, NULL, NULL),
('bak', 'ba', 'башҡорт теле', 'Bashkir', 'bachkir', NULL, NULL, NULL, NULL),
('bal', NULL, NULL, 'Baluchi', 'baloutchi', NULL, NULL, NULL, NULL),
('bam', 'bm', 'bamanankan', 'Bambara', 'bambara', NULL, NULL, NULL, NULL),
('ban', NULL, NULL, 'Balinese', 'balinais', NULL, NULL, NULL, NULL),
('baq', 'eu', 'euskara, euskera', 'Basque', 'basque', NULL, NULL, NULL, NULL),
('bas', NULL, NULL, 'Basa', 'basa', NULL, NULL, NULL, NULL),
('bat', NULL, NULL, 'Baltic languages', 'baltes, langues', NULL, NULL, NULL, NULL),
('bej', NULL, NULL, 'Beja; Bedawiyet', 'bedja', NULL, NULL, NULL, NULL),
('bel', 'be', 'беларуская мова', 'Belarusian', 'biélorusse', NULL, NULL, NULL, NULL),
('bem', NULL, NULL, 'Bemba', 'bemba', NULL, NULL, NULL, NULL),
('ben', 'bn', 'বাংলা', 'Bengali', 'bengali', NULL, NULL, NULL, NULL),
('ber', NULL, NULL, 'Berber languages', 'berbères, langues', NULL, NULL, NULL, NULL),
('bho', NULL, NULL, 'Bhojpuri', 'bhojpuri', NULL, NULL, NULL, NULL),
('bih', 'bh', 'भोजपुरी', 'Bihari', 'bihari', NULL, NULL, NULL, NULL),
('bik', NULL, NULL, 'Bikol', 'bikol', NULL, NULL, NULL, NULL),
('bin', NULL, NULL, 'Bini; Edo', 'bini; edo', NULL, NULL, NULL, NULL),
('bis', 'bi', 'Bislama', 'Bislama', 'bichlamar', NULL, NULL, NULL, NULL),
('bla', NULL, NULL, 'Siksika', 'blackfoot', NULL, NULL, NULL, NULL),
('bnt', NULL, NULL, 'Bantu languages', 'bantou, langues', NULL, NULL, NULL, NULL),
('bos', 'bs', 'bosanski jezik', 'Bosnian', 'bosniaque', NULL, NULL, NULL, NULL),
('bra', NULL, NULL, 'Braj', 'braj', NULL, NULL, NULL, NULL),
('bre', 'br', 'brezhoneg', 'Breton', 'breton', NULL, NULL, NULL, NULL),
('btk', NULL, NULL, 'Batak languages', 'batak, langues', NULL, NULL, NULL, NULL),
('bua', NULL, NULL, 'Buriat', 'bouriate', NULL, NULL, NULL, NULL),
('bug', NULL, NULL, 'Buginese', 'bugi', NULL, NULL, NULL, NULL),
('bul', 'bg', 'български език', 'Bulgarian', 'bulgare', NULL, NULL, NULL, NULL),
('bur', 'my', 'ဗမာစာ', 'Burmese', 'birman', NULL, NULL, NULL, NULL),
('byn', NULL, NULL, 'Blin; Bilin', 'blin; bilen', NULL, NULL, NULL, NULL),
('cad', NULL, NULL, 'Caddo', 'caddo', NULL, NULL, NULL, NULL),
('cai', NULL, NULL, 'Central American Indian languages', 'amérindiennes de l''Amérique centrale,  langues', NULL, NULL, NULL, NULL),
('car', NULL, NULL, 'Galibi Carib', 'karib; galibi; carib', NULL, NULL, NULL, NULL),
('cat', 'ca', 'català, valencià', 'Catalan; Valencian', 'catalan; valencien', NULL, NULL, NULL, NULL),
('cau', NULL, NULL, 'Caucasian languages', 'caucasiennes, langues', NULL, NULL, NULL, NULL),
('ceb', NULL, NULL, 'Cebuano', 'cebuano', NULL, NULL, NULL, NULL),
('cel', NULL, NULL, 'Celtic languages', 'celtiques, langues; celtes, langues', NULL, NULL, NULL, NULL),
('cha', 'ch', 'Chamoru', 'Chamorro', 'chamorro', NULL, NULL, NULL, NULL),
('chb', NULL, NULL, 'Chibcha', 'chibcha', NULL, NULL, NULL, NULL),
('che', 'ce', 'нохчийн мотт', 'Chechen', 'tchétchène', NULL, NULL, NULL, NULL),
('chg', NULL, NULL, 'Chagatai', 'djaghataï', NULL, NULL, NULL, NULL),
('chi', 'zh', '中文 (Zhōngwén), 汉语, 漢語', 'Chinese', 'chinois', NULL, NULL, NULL, NULL),
('chk', NULL, NULL, 'Chuukese', 'chuuk', NULL, NULL, NULL, NULL),
('chm', NULL, NULL, 'Mari', 'mari', NULL, NULL, NULL, NULL),
('chn', NULL, NULL, 'Chinook jargon', 'chinook, jargon', NULL, NULL, NULL, NULL),
('cho', NULL, NULL, 'Choctaw', 'choctaw', NULL, NULL, NULL, NULL),
('chp', NULL, NULL, 'Chipewyan; Dene Suline', 'chipewyan', NULL, NULL, NULL, NULL),
('chr', NULL, NULL, 'Cherokee', 'cherokee', NULL, NULL, NULL, NULL),
('chu', 'cu', 'ѩзыкъ словѣньскъ', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'slavon d''église; vieux slave; slavon liturgique; vieux bulgare', NULL, NULL, NULL, NULL),
('chv', 'cv', 'чӑваш чӗлхи', 'Chuvash', 'tchouvache', NULL, NULL, NULL, NULL),
('chy', NULL, NULL, 'Cheyenne', 'cheyenne', NULL, NULL, NULL, NULL),
('cmc', NULL, NULL, 'Chamic languages', 'chames, langues', NULL, NULL, NULL, NULL),
('cop', NULL, NULL, 'Coptic', 'copte', NULL, NULL, NULL, NULL),
('cor', 'kw', 'Kernewek', 'Cornish', 'cornique', NULL, NULL, NULL, NULL),
('cos', 'co', 'corsu, lingua corsa', 'Corsican', 'corse', NULL, NULL, NULL, NULL),
('cpe', NULL, NULL, 'Creoles and pidgins, English based', 'créoles et pidgins basés sur l''anglais', NULL, NULL, NULL, NULL),
('cpf', NULL, NULL, 'Creoles and pidgins, French-based', 'créoles et pidgins basés sur le français', NULL, NULL, NULL, NULL),
('cpp', NULL, NULL, 'Creoles and pidgins, Portuguese-based', 'créoles et pidgins basés sur le portugais', NULL, NULL, NULL, NULL),
('cre', 'cr', 'ᓀᐦᐃᔭᐍᐏᐣ', 'Cree', 'cree', NULL, NULL, NULL, NULL),
('crh', NULL, NULL, 'Crimean Tatar; Crimean Turkish', 'tatar de Crimé', NULL, NULL, NULL, NULL),
('crp', NULL, NULL, 'Creoles and pidgins', 'créoles et pidgins', NULL, NULL, NULL, NULL),
('csb', NULL, NULL, 'Kashubian', 'kachoube', NULL, NULL, NULL, NULL),
('cus', NULL, NULL, 'Cushitic languages', 'couchitiques,  langues', NULL, NULL, NULL, NULL),
('cze', 'cs', 'čeština, český jazyk', 'Czech', 'tchèque', NULL, NULL, NULL, NULL),
('dak', NULL, NULL, 'Dakota', 'dakota', NULL, NULL, NULL, NULL),
('dan', 'da', 'dansk', 'Danish', 'danois', NULL, NULL, NULL, NULL),
('dar', NULL, NULL, 'Dargwa', 'dargwa', NULL, NULL, NULL, NULL),
('day', NULL, NULL, 'Land Dayak languages', 'dayak, langues', NULL, NULL, NULL, NULL),
('del', NULL, NULL, 'Delaware', 'delaware', NULL, NULL, NULL, NULL),
('den', NULL, NULL, 'Slave (Athapascan)', 'esclave (athapascan)', NULL, NULL, NULL, NULL),
('dgr', NULL, NULL, 'Dogrib', 'dogrib', NULL, NULL, NULL, NULL),
('din', NULL, NULL, 'Dinka', 'dinka', NULL, NULL, NULL, NULL),
('div', 'dv', 'ދިވެހި', 'Divehi; Dhivehi; Maldivian', 'maldivien', NULL, NULL, NULL, NULL),
('doi', NULL, NULL, 'Dogri', 'dogri', NULL, NULL, NULL, NULL),
('dra', NULL, NULL, 'Dravidian languages', 'dravidiennes,  langues', NULL, NULL, NULL, NULL),
('dsb', NULL, NULL, 'Lower Sorbian', 'bas-sorabe', NULL, NULL, NULL, NULL),
('dua', NULL, NULL, 'Duala', 'douala', NULL, NULL, NULL, NULL),
('dum', NULL, NULL, 'Dutch, Middle (ca.1050-1350)', 'néerlandais moyen (ca. 1050-1350)', NULL, NULL, NULL, NULL),
('dut', 'nl', 'Nederlands, Vlaams', 'Dutch; Flemish', 'néerlandais; flamand', NULL, NULL, NULL, NULL),
('dyu', NULL, NULL, 'Dyula', 'dioula', NULL, NULL, NULL, NULL),
('dzo', 'dz', 'རྫོང་ཁ', 'Dzongkha', 'dzongkha', NULL, NULL, NULL, NULL),
('efi', NULL, NULL, 'Efik', 'efik', NULL, NULL, NULL, NULL),
('egy', NULL, NULL, 'Egyptian (Ancient)', 'égyptien', NULL, NULL, NULL, NULL),
('eka', NULL, NULL, 'Ekajuk', 'ekajuk', NULL, NULL, NULL, NULL),
('elx', NULL, NULL, 'Elamite', 'élamite', NULL, NULL, NULL, NULL),
('eng', 'en', 'English', 'English', 'anglais', NULL, NULL, NULL, 'Engels'),
('enm', NULL, NULL, 'English, Middle (1100-1500)', 'anglais moyen (1100-1500)', NULL, NULL, NULL, NULL),
('epo', 'eo', 'Esperanto', 'Esperanto', 'espéranto', NULL, NULL, NULL, NULL),
('est', 'et', 'eesti, eesti keel', 'Estonian', 'estonien', NULL, NULL, NULL, NULL),
('ewe', 'ee', 'Eʋegbe', 'Ewe', 'éwé', NULL, NULL, NULL, NULL),
('ewo', NULL, NULL, 'Ewondo', 'éwondo', NULL, NULL, NULL, NULL),
('fan', NULL, NULL, 'Fang', 'fang', NULL, NULL, NULL, NULL),
('fao', 'fo', 'føroyskt', 'Faroese', 'féroïen', NULL, NULL, NULL, NULL),
('fat', NULL, NULL, 'Fanti', 'fanti', NULL, NULL, NULL, NULL),
('fij', 'fj', 'vosa Vakaviti', 'Fijian', 'fidjien', NULL, NULL, NULL, NULL),
('fil', NULL, NULL, 'Filipino; Pilipino', 'filipino; pilipino', NULL, NULL, NULL, NULL),
('fin', 'fi', 'suomi, suomen kieli', 'Finnish', 'finnois', NULL, NULL, NULL, NULL),
('fiu', NULL, NULL, 'Finno-Ugrian languages', 'finno-ougriennes,  langues', NULL, NULL, NULL, NULL),
('fon', NULL, NULL, 'Fon', 'fon', NULL, NULL, NULL, NULL),
('fre', 'fr', 'français, langue française', 'French', 'français', NULL, NULL, NULL, NULL),
('frm', NULL, NULL, 'French, Middle (ca.1400-1600)', 'français moyen (1400-1600)', NULL, NULL, NULL, NULL),
('fro', NULL, NULL, 'French, Old (842-ca.1400)', 'français ancien (842-ca.1400)', NULL, NULL, NULL, NULL),
('frr', NULL, NULL, 'Northern Frisian', 'frison septentrional', NULL, NULL, NULL, NULL),
('frs', NULL, NULL, 'Eastern Frisian', 'frison oriental', NULL, NULL, NULL, NULL),
('fry', 'fy', 'Frysk', 'Western Frisian', 'frison occidental', NULL, NULL, NULL, NULL),
('ful', 'ff', 'Fulfulde, Pulaar, Pular', 'Fulah', 'peul', NULL, NULL, NULL, NULL),
('fur', NULL, NULL, 'Friulian', 'frioulan', NULL, NULL, NULL, NULL),
('gaa', NULL, NULL, 'Ga', 'ga', NULL, NULL, NULL, NULL),
('gay', NULL, NULL, 'Gayo', 'gayo', NULL, NULL, NULL, NULL),
('gba', NULL, NULL, 'Gbaya', 'gbaya', NULL, NULL, NULL, NULL),
('gem', NULL, NULL, 'Germanic languages', 'germaniques, langues', NULL, NULL, NULL, NULL),
('geo', 'ka', 'ქართული', 'Georgian', 'géorgien', NULL, NULL, NULL, NULL),
('ger', 'de', 'Deutsch', 'German', 'allemand', NULL, NULL, NULL, NULL),
('gez', NULL, NULL, 'Geez', 'guèze', NULL, NULL, NULL, NULL),
('gil', NULL, NULL, 'Gilbertese', 'kiribati', NULL, NULL, NULL, NULL),
('gla', 'gd', 'Gàidhlig', 'Gaelic; Scottish Gaelic', 'gaélique; gaélique écossais', NULL, NULL, NULL, NULL),
('gle', 'ga', 'Gaeilge', 'Irish', 'irlandais', NULL, NULL, NULL, NULL),
('glg', 'gl', 'galego', 'Galician', 'galicien', NULL, NULL, NULL, NULL),
('glv', 'gv', 'Gaelg, Gailck', 'Manx', 'manx; mannois', NULL, NULL, NULL, NULL),
('gmh', NULL, NULL, 'German, Middle High (ca.1050-1500)', 'allemand, moyen haut (ca. 1050-1500)', NULL, NULL, NULL, NULL),
('goh', NULL, NULL, 'German, Old High (ca.750-1050)', 'allemand, vieux haut (ca. 750-1050)', NULL, NULL, NULL, NULL),
('gon', NULL, NULL, 'Gondi', 'gond', NULL, NULL, NULL, NULL),
('gor', NULL, NULL, 'Gorontalo', 'gorontalo', NULL, NULL, NULL, NULL),
('got', NULL, NULL, 'Gothic', 'gothique', NULL, NULL, NULL, NULL),
('grb', NULL, NULL, 'Grebo', 'grebo', NULL, NULL, NULL, NULL),
('grc', NULL, NULL, 'Greek, Ancient (to 1453)', 'grec ancien (jusqu''à 1453)', NULL, NULL, NULL, NULL),
('gre', 'el', 'ελληνικά', 'Greek, Modern (1453-)', 'grec moderne (après 1453)', NULL, NULL, NULL, NULL),
('grn', 'gn', NULL, 'Guarani', 'guarani', NULL, NULL, NULL, NULL),
('gsw', NULL, NULL, 'Swiss German; Alemannic; Alsatian', 'suisse alémanique; alémanique; alsacien', NULL, NULL, NULL, NULL),
('guj', 'gu', 'ગુજરાતી', 'Gujarati', 'goudjrati', NULL, NULL, NULL, NULL),
('gwi', NULL, NULL, 'Gwich''in', 'gwich''in', NULL, NULL, NULL, NULL),
('hai', NULL, NULL, 'Haida', 'haida', NULL, NULL, NULL, NULL),
('hat', 'ht', 'Kreyòl ayisyen', 'Haitian; Haitian Creole', 'haïtien; créole haïtien', NULL, NULL, NULL, NULL),
('hau', 'ha', '(Hausa) هَوُسَ', 'Hausa', 'haoussa', NULL, NULL, NULL, NULL),
('haw', NULL, NULL, 'Hawaiian', 'hawaïen', NULL, NULL, NULL, NULL),
('heb', 'he', 'עברית', 'Hebrew', 'hébreu', NULL, NULL, NULL, NULL),
('her', 'hz', 'Otjiherero', 'Herero', 'herero', NULL, NULL, NULL, NULL),
('hil', NULL, NULL, 'Hiligaynon', 'hiligaynon', NULL, NULL, NULL, NULL),
('him', NULL, NULL, 'Himachali', 'himachali', NULL, NULL, NULL, NULL),
('hin', 'hi', 'हिन्दी, हिंदी', 'Hindi', 'hindi', NULL, NULL, NULL, NULL),
('hit', NULL, NULL, 'Hittite', 'hittite', NULL, NULL, NULL, NULL),
('hmn', NULL, NULL, 'Hmong', 'hmong', NULL, NULL, NULL, NULL),
('hmo', 'ho', 'Hiri Motu', 'Hiri Motu', 'hiri motu', NULL, NULL, NULL, NULL),
('hrv', 'hr', 'hrvatski jezik', 'Croatian', 'croate', NULL, NULL, NULL, NULL),
('hsb', NULL, NULL, 'Upper Sorbian', 'haut-sorabe', NULL, NULL, NULL, NULL),
('hun', 'hu', 'magyar', 'Hungarian', 'hongrois', NULL, NULL, NULL, NULL),
('hup', NULL, NULL, 'Hupa', 'hupa', NULL, NULL, NULL, NULL),
('iba', NULL, NULL, 'Iban', 'iban', NULL, NULL, NULL, NULL),
('ibo', 'ig', 'Asụsụ Igbo', 'Igbo', 'igbo', NULL, NULL, NULL, NULL),
('ice', 'is', 'Íslenska', 'Icelandic', 'islandais', NULL, NULL, NULL, NULL),
('ido', 'io', 'Ido', 'Ido', 'ido', NULL, NULL, NULL, NULL),
('iii', 'ii', 'ꆈꌠ꒿ Nuosuhxop', 'Sichuan Yi; Nuosu', 'yi de Sichuan', NULL, NULL, NULL, NULL),
('ijo', NULL, NULL, 'Ijo languages', 'ijo, langues', NULL, NULL, NULL, NULL),
('iku', 'iu', 'ᐃᓄᒃᑎᑐᑦ', 'Inuktitut', 'inuktitut', NULL, NULL, NULL, NULL),
('ile', 'ie', 'Originally called Occidental; then Interlingue after WWII', 'Interlingue; Occidental', 'interlingue', NULL, NULL, NULL, NULL),
('ilo', NULL, NULL, 'Iloko', 'ilocano', NULL, NULL, NULL, NULL),
('ina', 'ia', 'Interlingua', 'Interlingua (International Auxiliary Language Association)', 'interlingua (langue auxiliaire internationale)', NULL, NULL, NULL, NULL),
('inc', NULL, NULL, 'Indic languages', 'indo-aryennes, langues', NULL, NULL, NULL, NULL),
('ind', 'id', 'Bahasa Indonesia', 'Indonesian', 'indonésien', NULL, NULL, NULL, NULL),
('ine', NULL, NULL, 'Indo-European languages', 'indo-européennes, langues', NULL, NULL, NULL, NULL),
('inh', NULL, NULL, 'Ingush', 'ingouche', NULL, NULL, NULL, NULL),
('ipk', 'ik', 'Iñupiaq, Iñupiatun', 'Inupiaq', 'inupiaq', NULL, NULL, NULL, NULL),
('ira', NULL, NULL, 'Iranian languages', 'iraniennes, langues', NULL, NULL, NULL, NULL),
('iro', NULL, NULL, 'Iroquoian languages', 'iroquoises, langues', NULL, NULL, NULL, NULL),
('ita', 'it', 'italiano', 'Italian', 'italien', NULL, NULL, NULL, NULL),
('jav', 'jv', 'basa Jawa', 'Javanese', 'javanais', NULL, NULL, NULL, NULL),
('jbo', NULL, NULL, 'Lojban', 'lojban', NULL, NULL, NULL, NULL),
('jpn', 'ja', '日本語 (にほんご)', 'Japanese', 'japonais', NULL, NULL, NULL, NULL),
('jpr', NULL, NULL, 'Judeo-Persian', 'judéo-persan', NULL, NULL, NULL, NULL),
('jrb', NULL, NULL, 'Judeo-Arabic', 'judéo-arabe', NULL, NULL, NULL, NULL),
('kaa', NULL, NULL, 'Kara-Kalpak', 'karakalpak', NULL, NULL, NULL, NULL),
('kab', NULL, NULL, 'Kabyle', 'kabyle', NULL, NULL, NULL, NULL),
('kac', NULL, NULL, 'Kachin; Jingpho', 'kachin; jingpho', NULL, NULL, NULL, NULL),
('kal', 'kl', 'kalaallisut, kalaallit oqaasii', 'Kalaallisut; Greenlandic', 'groenlandais', NULL, NULL, NULL, NULL),
('kam', NULL, NULL, 'Kamba', 'kamba', NULL, NULL, NULL, NULL),
('kan', 'kn', 'ಕನ್ನಡ', 'Kannada', 'kannada', NULL, NULL, NULL, NULL),
('kar', NULL, NULL, 'Karen languages', 'karen, langues', NULL, NULL, NULL, NULL),
('kas', 'ks', 'कश्मीरी, كشميري‎', 'Kashmiri', 'kashmiri', NULL, NULL, NULL, NULL),
('kau', 'kr', 'Kanuri', 'Kanuri', 'kanouri', NULL, NULL, NULL, NULL),
('kaw', NULL, NULL, 'Kawi', 'kawi', NULL, NULL, NULL, NULL),
('kaz', 'kk', 'қазақ тілі', 'Kazakh', 'kazakh', NULL, NULL, NULL, NULL),
('kbd', NULL, NULL, 'Kabardian', 'kabardien', NULL, NULL, NULL, NULL),
('kha', NULL, NULL, 'Khasi', 'khasi', NULL, NULL, NULL, NULL),
('khi', NULL, NULL, 'Khoisan languages', 'khoïsan, langues', NULL, NULL, NULL, NULL),
('khm', 'km', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'Central Khmer', 'khmer central', NULL, NULL, NULL, NULL),
('kho', NULL, NULL, 'Khotanese; Sakan', 'khotanais; sakan', NULL, NULL, NULL, NULL),
('kik', 'ki', 'Gĩkũyũ', 'Kikuyu; Gikuyu', 'kikuyu', NULL, NULL, NULL, NULL),
('kin', 'rw', 'Ikinyarwanda', 'Kinyarwanda', 'rwanda', NULL, NULL, NULL, NULL),
('kir', 'ky', 'Кыргызча, Кыргыз тили', 'Kirghiz; Kyrgyz', 'kirghiz', NULL, NULL, NULL, NULL),
('kmb', NULL, NULL, 'Kimbundu', 'kimbundu', NULL, NULL, NULL, NULL),
('kok', NULL, NULL, 'Konkani', 'konkani', NULL, NULL, NULL, NULL),
('kom', 'kv', 'коми кыв', 'Komi', 'kom', NULL, NULL, NULL, NULL),
('kon', 'kg', 'Kikongo', 'Kongo', 'kongo', NULL, NULL, NULL, NULL),
('kor', 'ko', '한국어, 조선어', 'Korean', 'coréen', NULL, NULL, NULL, NULL),
('kos', NULL, NULL, 'Kosraean', 'kosrae', NULL, NULL, NULL, NULL),
('kpe', NULL, NULL, 'Kpelle', 'kpellé', NULL, NULL, NULL, NULL),
('krc', NULL, NULL, 'Karachay-Balkar', 'karatchai balkar', NULL, NULL, NULL, NULL),
('krl', NULL, NULL, 'Karelian', 'carélien', NULL, NULL, NULL, NULL),
('kro', NULL, NULL, 'Kru languages', 'krou, langues', NULL, NULL, NULL, NULL),
('kru', NULL, NULL, 'Kurukh', 'kurukh', NULL, NULL, NULL, NULL),
('kua', 'kj', 'Kuanyama', 'Kuanyama; Kwanyama', 'kuanyama; kwanyama', NULL, NULL, NULL, NULL),
('kum', NULL, NULL, 'Kumyk', 'koumyk', NULL, NULL, NULL, NULL),
('kur', 'ku', 'Kurdî, كوردی‎', 'Kurdish', 'kurde', NULL, NULL, NULL, NULL),
('kut', NULL, NULL, 'Kutenai', 'kutenai', NULL, NULL, NULL, NULL),
('lad', NULL, NULL, 'Ladino', 'judéo-espagnol', NULL, NULL, NULL, NULL),
('lah', NULL, NULL, 'Lahnda', 'lahnda', NULL, NULL, NULL, NULL),
('lam', NULL, NULL, 'Lamba', 'lamba', NULL, NULL, NULL, NULL),
('lao', 'lo', 'ພາສາລາວ', 'Lao', 'lao', NULL, NULL, NULL, NULL),
('lat', 'la', 'latine, lingua latina', 'Latin', 'latin', NULL, NULL, NULL, NULL),
('lav', 'lv', 'latviešu valoda', 'Latvian', 'letton', NULL, NULL, NULL, NULL),
('lez', NULL, NULL, 'Lezghian', 'lezghien', NULL, NULL, NULL, NULL),
('lim', 'li', 'Limburgs', 'Limburgan; Limburger; Limburgish', 'limbourgeois', NULL, NULL, NULL, NULL),
('lin', 'ln', 'Lingála', 'Lingala', 'lingala', NULL, NULL, NULL, NULL),
('lit', 'lt', 'lietuvių kalba', 'Lithuanian', 'lituanien', NULL, NULL, NULL, NULL),
('lol', NULL, NULL, 'Mongo', 'mongo', NULL, NULL, NULL, NULL),
('loz', NULL, NULL, 'Lozi', 'lozi', NULL, NULL, NULL, NULL),
('ltz', 'lb', 'Lëtzebuergesch', 'Luxembourgish; Letzeburgesch', 'luxembourgeois', NULL, NULL, NULL, NULL),
('lua', NULL, NULL, 'Luba-Lulua', 'luba-lulua', NULL, NULL, NULL, NULL),
('lub', 'lu', 'Tshiluba', 'Luba-Katanga', 'luba-katanga', NULL, NULL, NULL, NULL),
('lug', 'lg', 'Luganda', 'Ganda', 'ganda', NULL, NULL, NULL, NULL),
('lui', NULL, NULL, 'Luiseno', 'luiseno', NULL, NULL, NULL, NULL),
('lun', NULL, NULL, 'Lunda', 'lunda', NULL, NULL, NULL, NULL),
('luo', NULL, NULL, 'Luo (Kenya and Tanzania)', 'luo (Kenya et Tanzanie)', NULL, NULL, NULL, NULL),
('lus', NULL, NULL, 'Lushai', 'lushai', NULL, NULL, NULL, NULL),
('mac', 'mk', 'македонски јазик', 'Macedonian', 'macédonien', NULL, NULL, NULL, NULL),
('mad', NULL, NULL, 'Madurese', 'madourais', NULL, NULL, NULL, NULL),
('mag', NULL, NULL, 'Magahi', 'magahi', NULL, NULL, NULL, NULL),
('mah', 'mh', 'Kajin M̧ajeļ', 'Marshallese', 'marshall', NULL, NULL, NULL, NULL),
('mai', NULL, NULL, 'Maithili', 'maithili', NULL, NULL, NULL, NULL),
('mak', NULL, NULL, 'Makasar', 'makassar', NULL, NULL, NULL, NULL),
('mal', 'ml', 'മലയാളം', 'Malayalam', 'malayalam', NULL, NULL, NULL, NULL),
('man', NULL, NULL, 'Mandingo', 'mandingue', NULL, NULL, NULL, NULL),
('mao', 'mi', 'te reo Māori', 'Maori', 'maori', NULL, NULL, NULL, NULL),
('map', NULL, NULL, 'Austronesian languages', 'austronésiennes, langues', NULL, NULL, NULL, NULL),
('mar', 'mr', 'मराठी', 'Marathi', 'marathe', NULL, NULL, NULL, NULL),
('mas', NULL, NULL, 'Masai', 'massaï', NULL, NULL, NULL, NULL),
('may', 'ms', 'bahasa Melayu, بهاس ملايو‎', 'Malay', 'malais', NULL, NULL, NULL, NULL),
('mdf', NULL, NULL, 'Moksha', 'moksa', NULL, NULL, NULL, NULL),
('mdr', NULL, NULL, 'Mandar', 'mandar', NULL, NULL, NULL, NULL),
('men', NULL, NULL, 'Mende', 'mendé', NULL, NULL, NULL, NULL),
('mga', NULL, NULL, 'Irish, Middle (900-1200)', 'irlandais moyen (900-1200)', NULL, NULL, NULL, NULL),
('mic', NULL, NULL, 'Mi''kmaq; Micmac', 'mi''kmaq; micmac', NULL, NULL, NULL, NULL),
('min', NULL, NULL, 'Minangkabau', 'minangkabau', NULL, NULL, NULL, NULL),
('mis', NULL, NULL, 'Uncoded languages', 'langues non codées', NULL, NULL, NULL, NULL),
('mkh', NULL, NULL, 'Mon-Khmer languages', 'môn-khmer, langues', NULL, NULL, NULL, NULL),
('mlg', 'mg', 'fiteny malagasy', 'Malagasy', 'malgache', NULL, NULL, NULL, NULL),
('mlt', 'mt', 'Malti', 'Maltese', 'maltais', NULL, NULL, NULL, NULL),
('mnc', NULL, NULL, 'Manchu', 'mandchou', NULL, NULL, NULL, NULL),
('mni', NULL, NULL, 'Manipuri', 'manipuri', NULL, NULL, NULL, NULL),
('mno', NULL, NULL, 'Manobo languages', 'manobo, langues', NULL, NULL, NULL, NULL),
('moh', NULL, NULL, 'Mohawk', 'mohawk', NULL, NULL, NULL, NULL),
('mon', 'mn', 'монгол', 'Mongolian', 'mongol', NULL, NULL, NULL, NULL),
('mos', NULL, NULL, 'Mossi', 'moré', NULL, NULL, NULL, NULL),
('mul', NULL, NULL, 'Multiple languages', 'multilingue', NULL, NULL, NULL, NULL),
('mun', NULL, NULL, 'Munda languages', 'mounda, langues', NULL, NULL, NULL, NULL),
('mus', NULL, NULL, 'Creek', 'muskogee', NULL, NULL, NULL, NULL),
('mwl', NULL, NULL, 'Mirandese', 'mirandais', NULL, NULL, NULL, NULL),
('mwr', NULL, NULL, 'Marwari', 'marvari', NULL, NULL, NULL, NULL),
('myn', NULL, NULL, 'Mayan languages', 'maya, langues', NULL, NULL, NULL, NULL),
('myv', NULL, NULL, 'Erzya', 'erza', NULL, NULL, NULL, NULL),
('nah', NULL, NULL, 'Nahuatl languages', 'nahuatl, langues', NULL, NULL, NULL, NULL),
('nai', NULL, NULL, 'North American Indian languages', 'nord-amérindiennes, langues', NULL, NULL, NULL, NULL),
('nap', NULL, NULL, 'Neapolitan', 'napolitain', NULL, NULL, NULL, NULL),
('nau', 'na', 'Ekakairũ Naoero', 'Nauru', 'nauruan', NULL, NULL, NULL, NULL),
('nav', 'nv', 'Diné bizaad, Dinékʼehǰí', 'Navajo; Navaho', 'navaho', NULL, NULL, NULL, NULL),
('nbl', 'nr', 'isiNdebele', 'Ndebele, South; South Ndebele', 'ndébélé du Sud', NULL, NULL, NULL, NULL),
('nde', 'nd', 'isiNdebele', 'Ndebele, North; North Ndebele', 'ndébélé du Nord', NULL, NULL, NULL, NULL),
('ndo', 'ng', 'Owambo', 'Ndonga', 'ndonga', NULL, NULL, NULL, NULL),
('nds', NULL, NULL, 'Low German; Low Saxon; German, Low; Saxon, Low', 'bas allemand; bas saxon; allemand, bas; saxon, bas', NULL, NULL, NULL, NULL),
('nep', 'ne', 'नेपाली', 'Nepali', 'népalais', NULL, NULL, NULL, NULL),
('new', NULL, NULL, 'Nepal Bhasa; Newari', 'nepal bhasa; newari', NULL, NULL, NULL, NULL),
('nia', NULL, NULL, 'Nias', 'nias', NULL, NULL, NULL, NULL),
('nic', NULL, NULL, 'Niger-Kordofanian languages', 'nigéro-kordofaniennes, langues', NULL, NULL, NULL, NULL),
('niu', NULL, NULL, 'Niuean', 'niué', NULL, NULL, NULL, NULL),
('nno', 'nn', 'Norsk nynorsk', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'norvégien nynorsk; nynorsk, norvégien', NULL, NULL, NULL, NULL),
('nob', 'nb', 'Norsk bokmål', 'Bokmål, Norwegian; Norwegian Bokmål', 'norvégien bokmål', NULL, NULL, NULL, NULL),
('nog', NULL, NULL, 'Nogai', 'nogaï; nogay', NULL, NULL, NULL, NULL),
('non', NULL, NULL, 'Norse, Old', 'norrois, vieux', NULL, NULL, NULL, NULL),
('nor', 'no', 'Norsk', 'Norwegian', 'norvégien', NULL, NULL, NULL, NULL),
('nqo', NULL, NULL, 'N''Ko', 'n''ko', NULL, NULL, NULL, NULL),
('nso', NULL, NULL, 'Pedi; Sepedi; Northern Sotho', 'pedi; sepedi; sotho du Nord', NULL, NULL, NULL, NULL),
('nub', NULL, NULL, 'Nubian languages', 'nubiennes, langues', NULL, NULL, NULL, NULL),
('nwc', NULL, NULL, 'Classical Newari; Old Newari; Classical Nepal Bhasa', 'newari classique', NULL, NULL, NULL, NULL),
('nya', 'ny', 'chiCheŵa, chinyanja', 'Chichewa; Chewa; Nyanja', 'chichewa; chewa; nyanja', NULL, NULL, NULL, NULL),
('nym', NULL, NULL, 'Nyamwezi', 'nyamwezi', NULL, NULL, NULL, NULL),
('nyn', NULL, NULL, 'Nyankole', 'nyankolé', NULL, NULL, NULL, NULL),
('nyo', NULL, NULL, 'Nyoro', 'nyoro', NULL, NULL, NULL, NULL),
('nzi', NULL, NULL, 'Nzima', 'nzema', NULL, NULL, NULL, NULL),
('oci', 'oc', NULL, 'Occitan (post 1500)', 'occitan (après 1500)', NULL, NULL, NULL, NULL),
('oji', 'oj', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'Ojibwa', 'ojibwa', NULL, NULL, NULL, NULL),
('ori', 'or', 'ଓଡ଼ିଆ', 'Oriya', 'oriya', NULL, NULL, NULL, NULL),
('orm', 'om', 'Afaan Oromoo', 'Oromo', 'galla', NULL, NULL, NULL, NULL),
('osa', NULL, NULL, 'Osage', 'osage', NULL, NULL, NULL, NULL),
('oss', 'os', 'ирон æвзаг', 'Ossetian; Ossetic', 'ossète', NULL, NULL, NULL, NULL),
('ota', NULL, NULL, 'Turkish, Ottoman (1500-1928)', 'turc ottoman (1500-1928)', NULL, NULL, NULL, NULL),
('oto', NULL, NULL, 'Otomian languages', 'otomi, langues', NULL, NULL, NULL, NULL),
('paa', NULL, NULL, 'Papuan languages', 'papoues, langues', NULL, NULL, NULL, NULL),
('pag', NULL, NULL, 'Pangasinan', 'pangasinan', NULL, NULL, NULL, NULL),
('pal', NULL, NULL, 'Pahlavi', 'pahlavi', NULL, NULL, NULL, NULL),
('pam', NULL, NULL, 'Pampanga; Kapampangan', 'pampangan', NULL, NULL, NULL, NULL),
('pan', 'pa', 'ਪੰਜਾਬੀ, پنجابی‎', 'Panjabi; Punjabi', 'pendjabi', NULL, NULL, NULL, NULL),
('pap', NULL, NULL, 'Papiamento', 'papiamento', NULL, NULL, NULL, NULL),
('pau', NULL, NULL, 'Palauan', 'palau', NULL, NULL, NULL, NULL),
('peo', NULL, NULL, 'Persian, Old (ca.600-400 B.C.)', 'perse, vieux (ca. 600-400 av. J.-C.)', NULL, NULL, NULL, NULL),
('per', 'fa', 'فارسی', 'Persian', 'persan', NULL, NULL, NULL, NULL),
('phi', NULL, NULL, 'Philippine languages', 'philippines, langues', NULL, NULL, NULL, NULL),
('phn', NULL, NULL, 'Phoenician', 'phénicien', NULL, NULL, NULL, NULL),
('pli', 'pi', 'पाऴि', 'Pali', 'pali', NULL, NULL, NULL, NULL),
('pol', 'pl', 'język polski, polszczyzna', 'Polish', 'polonais', NULL, NULL, NULL, NULL),
('pon', NULL, NULL, 'Pohnpeian', 'pohnpei', NULL, NULL, NULL, NULL),
('por', 'pt', 'português', 'Portuguese', 'portugais', NULL, NULL, NULL, NULL),
('pra', NULL, NULL, 'Prakrit languages', 'prâkrit, langues', NULL, NULL, NULL, NULL),
('pro', NULL, NULL, 'Provençal, Old (to 1500);Occitan, Old (to 1500)', 'provençal ancien (jusqu''à 1500); occitan ancien (jusqu''à 1500)', NULL, NULL, NULL, NULL),
('pus', 'ps', 'پښتو', 'Pushto; Pashto', 'pachto', NULL, NULL, NULL, NULL),
('qaa', NULL, NULL, 'Reserved for local use', 'réservée à l''usage local', NULL, NULL, NULL, NULL),
('que', 'qu', 'Runa Simi, Kichwa', 'Quechua', 'quechua', NULL, NULL, NULL, NULL),
('raj', NULL, NULL, 'Rajasthani', 'rajasthani', NULL, NULL, NULL, NULL),
('rap', NULL, NULL, 'Rapanui', 'rapanui', NULL, NULL, NULL, NULL),
('rar', NULL, NULL, 'Rarotongan; Cook Islands Maori', 'rarotonga; maori des îles Cook', NULL, NULL, NULL, NULL),
('roa', NULL, NULL, 'Romance languages', 'romanes, langues', NULL, NULL, NULL, NULL),
('roh', 'rm', 'rumantsch grischun', 'Romansh', 'romanche', NULL, NULL, NULL, NULL),
('rom', NULL, NULL, 'Romany', 'tsigane', NULL, NULL, NULL, NULL),
('rum', 'ro', 'limba română', 'Romanian; Moldavian; Moldovan', 'roumain; moldave', NULL, NULL, NULL, NULL),
('run', 'rn', 'Ikirundi', 'Rundi', 'rundi', NULL, NULL, NULL, NULL),
('rup', NULL, NULL, 'Aromanian; Arumanian; Macedo-Romanian', 'aroumain; macédo-roumain', NULL, NULL, NULL, NULL),
('rus', 'ru', 'русский язык', 'Russian', 'russe', NULL, NULL, NULL, NULL),
('sad', NULL, NULL, 'Sandawe', 'sandawe', NULL, NULL, NULL, NULL),
('sag', 'sg', 'yângâ tî sängö', 'Sango', 'sango', NULL, NULL, NULL, NULL),
('sah', NULL, NULL, 'Yakut', 'iakoute', NULL, NULL, NULL, NULL),
('sai', NULL, NULL, 'South American Indian languages', 'sud-amérindiennes, langues', NULL, NULL, NULL, NULL),
('sal', NULL, NULL, 'Salishan languages', 'salishennes, langues', NULL, NULL, NULL, NULL),
('sam', NULL, NULL, 'Samaritan Aramaic', 'samaritain', NULL, NULL, NULL, NULL),
('san', 'sa', 'संस्कृतम्', 'Sanskrit', 'sanskrit', NULL, NULL, NULL, NULL),
('sas', NULL, NULL, 'Sasak', 'sasak', NULL, NULL, NULL, NULL),
('sat', NULL, NULL, 'Santali', 'santal', NULL, NULL, NULL, NULL),
('scn', NULL, NULL, 'Sicilian', 'sicilien', NULL, NULL, NULL, NULL),
('sco', NULL, NULL, 'Scots', 'écossais', NULL, NULL, NULL, NULL),
('sel', NULL, NULL, 'Selkup', 'selkoupe', NULL, NULL, NULL, NULL),
('sem', NULL, NULL, 'Semitic languages', 'sémitiques, langues', NULL, NULL, NULL, NULL),
('sga', NULL, NULL, 'Irish, Old (to 900)', 'irlandais ancien (jusqu''à 900)', NULL, NULL, NULL, NULL),
('sgn', NULL, NULL, 'Sign Languages', 'langues des signes', NULL, NULL, NULL, NULL),
('shn', NULL, NULL, 'Shan', 'chan', NULL, NULL, NULL, NULL),
('sid', NULL, NULL, 'Sidamo', 'sidamo', NULL, NULL, NULL, NULL),
('sin', 'si', 'සිංහල', 'Sinhala; Sinhalese', 'singhalais', NULL, NULL, NULL, NULL),
('sio', NULL, NULL, 'Siouan languages', 'sioux, langues', NULL, NULL, NULL, NULL),
('sit', NULL, NULL, 'Sino-Tibetan languages', 'sino-tibétaines, langues', NULL, NULL, NULL, NULL),
('sla', NULL, NULL, 'Slavic languages', 'slaves, langues', NULL, NULL, NULL, NULL),
('slo', 'sk', 'slovenčina, slovenský jazyk', 'Slovak', 'slovaque', NULL, NULL, NULL, NULL),
('slv', 'sl', 'slovenski jezik, slovenščina', 'Slovenian', 'slovène', NULL, NULL, NULL, NULL),
('sma', NULL, NULL, 'Southern Sami', 'sami du Sud', NULL, NULL, NULL, NULL),
('sme', 'se', 'Davvisámegiella', 'Northern Sami', 'sami du Nord', NULL, NULL, NULL, NULL),
('smi', NULL, NULL, 'Sami languages', 'sames, langues', NULL, NULL, NULL, NULL),
('smj', NULL, NULL, 'Lule Sami', 'sami de Lule', NULL, NULL, NULL, NULL),
('smn', NULL, NULL, 'Inari Sami', 'sami d''Inari', NULL, NULL, NULL, NULL),
('smo', 'sm', NULL, 'Samoan', 'samoan', NULL, NULL, NULL, NULL),
('sms', NULL, NULL, 'Skolt Sami', 'sami skolt', NULL, NULL, NULL, NULL),
('sna', 'sn', 'chiShona', 'Shona', 'shona', NULL, NULL, NULL, NULL),
('snd', 'sd', 'सिन्धी, سنڌي، سندھی‎', 'Sindhi', 'sindhi', NULL, NULL, NULL, NULL),
('snk', NULL, NULL, 'Soninke', 'soninké', NULL, NULL, NULL, NULL),
('sog', NULL, NULL, 'Sogdian', 'sogdien', NULL, NULL, NULL, NULL),
('som', 'so', 'Soomaaliga, af Soomaali', 'Somali', 'somali', NULL, NULL, NULL, NULL),
('son', NULL, NULL, 'Songhai languages', 'songhai, langues', NULL, NULL, NULL, NULL),
('sot', 'st', 'Sesotho', 'Sotho, Southern', 'sotho du Sud', NULL, NULL, NULL, NULL),
('spa', 'es', 'español, castellano', 'Spanish; Castilian', 'espagnol; castillan', NULL, NULL, NULL, NULL),
('srd', 'sc', 'sardu', 'Sardinian', 'sarde', NULL, NULL, NULL, NULL),
('srn', NULL, NULL, 'Sranan Tongo', 'sranan tongo', NULL, NULL, NULL, NULL),
('srp', 'sr', 'српски језик', 'Serbian', 'serbe', NULL, NULL, NULL, NULL),
('srr', NULL, NULL, 'Serer', 'sérère', NULL, NULL, NULL, NULL),
('ssa', NULL, NULL, 'Nilo-Saharan languages', 'nilo-sahariennes, langues', NULL, NULL, NULL, NULL),
('ssw', 'ss', 'SiSwati', 'Swati', 'swati', NULL, NULL, NULL, NULL),
('suk', NULL, NULL, 'Sukuma', 'sukuma', NULL, NULL, NULL, NULL),
('sun', 'su', 'Basa Sunda', 'Sundanese', 'soundanais', NULL, NULL, NULL, NULL),
('sus', NULL, NULL, 'Susu', 'soussou', NULL, NULL, NULL, NULL),
('sux', NULL, NULL, 'Sumerian', 'sumérien', NULL, NULL, NULL, NULL),
('swa', 'sw', 'Kiswahili', 'Swahili', 'swahili', NULL, NULL, NULL, NULL),
('swe', 'sv', 'Svenska', 'Swedish', 'suédois', NULL, NULL, NULL, NULL),
('syc', NULL, NULL, 'Classical Syriac', 'syriaque classique', NULL, NULL, NULL, NULL),
('syr', NULL, NULL, 'Syriac', 'syriaque', NULL, NULL, NULL, NULL),
('tah', 'ty', 'Reo Tahiti', 'Tahitian', 'tahitien', NULL, NULL, NULL, NULL),
('tai', NULL, NULL, 'Tai languages', 'tai, langues', NULL, NULL, NULL, NULL),
('tam', 'ta', 'தமிழ்', 'Tamil', 'tamoul', NULL, NULL, NULL, NULL),
('tat', 'tt', 'татар теле, tatar tele', 'Tatar', 'tatar', NULL, NULL, NULL, NULL),
('tel', 'te', 'తెలుగు', 'Telugu', 'télougou', NULL, NULL, NULL, NULL),
('tem', NULL, NULL, 'Timne', 'temne', NULL, NULL, NULL, NULL),
('ter', NULL, NULL, 'Tereno', 'tereno', NULL, NULL, NULL, NULL),
('tet', NULL, NULL, 'Tetum', 'tetum', NULL, NULL, NULL, NULL),
('tgk', 'tg', 'тоҷикӣ, toğikī, تاجیکی‎', 'Tajik', 'tadjik', NULL, NULL, NULL, NULL),
('tgl', 'tl', 'Wikang Tagalog', 'Tagalog', 'tagalog', NULL, NULL, NULL, NULL),
('tha', 'th', 'ไทย', 'Thai', 'thaï', NULL, NULL, NULL, NULL),
('tib', 'bo', 'བོད་ཡིག', 'Tibetan', 'tibétain', NULL, NULL, NULL, NULL),
('tig', NULL, NULL, 'Tigre', 'tigré', NULL, NULL, NULL, NULL),
('tir', 'ti', 'ትግርኛ', 'Tigrinya', 'tigrigna', NULL, NULL, NULL, NULL),
('tiv', NULL, NULL, 'Tiv', 'tiv', NULL, NULL, NULL, NULL),
('tkl', NULL, NULL, 'Tokelau', 'tokelau', NULL, NULL, NULL, NULL),
('tlh', NULL, NULL, 'Klingon; tlhIngan-Hol', 'klingon', NULL, NULL, NULL, NULL),
('tli', NULL, NULL, 'Tlingit', 'tlingit', NULL, NULL, NULL, NULL),
('tmh', NULL, NULL, 'Tamashek', 'tamacheq', NULL, NULL, NULL, NULL),
('tog', NULL, NULL, 'Tonga (Nyasa)', 'tonga (Nyasa)', NULL, NULL, NULL, NULL),
('ton', 'to', 'faka Tonga', 'Tonga (Tonga Islands)', 'tongan (Îles Tonga)', NULL, NULL, NULL, NULL),
('tpi', NULL, NULL, 'Tok Pisin', 'tok pisin', NULL, NULL, NULL, NULL),
('tsi', NULL, NULL, 'Tsimshian', 'tsimshian', NULL, NULL, NULL, NULL),
('tsn', 'tn', 'Setswana', 'Tswana', 'tswana', NULL, NULL, NULL, NULL),
('tso', 'ts', 'Xitsonga', 'Tsonga', 'tsonga', NULL, NULL, NULL, NULL),
('tuk', 'tk', 'Türkmen, Түркмен', 'Turkmen', 'turkmène', NULL, NULL, NULL, NULL),
('tum', NULL, NULL, 'Tumbuka', 'tumbuka', NULL, NULL, NULL, NULL),
('tup', NULL, NULL, 'Tupi languages', 'tupi, langues', NULL, NULL, NULL, NULL),
('tur', 'tr', 'Türkçe', 'Turkish', 'turc', NULL, NULL, NULL, NULL),
('tut', NULL, NULL, 'Altaic languages', 'altaïques, langues', NULL, NULL, NULL, NULL),
('tvl', NULL, NULL, 'Tuvalu', 'tuvalu', NULL, NULL, NULL, NULL),
('twi', 'tw', 'Twi', 'Twi', 'twi', NULL, NULL, NULL, NULL),
('tyv', NULL, NULL, 'Tuvinian', 'touva', NULL, NULL, NULL, NULL),
('udm', NULL, NULL, 'Udmurt', 'oudmourte', NULL, NULL, NULL, NULL),
('uga', NULL, NULL, 'Ugaritic', 'ougaritique', NULL, NULL, NULL, NULL),
('uig', 'ug', 'Uyƣurqə, ئۇيغۇرچە‎', 'Uighur; Uyghur', 'ouïgour', NULL, NULL, NULL, NULL),
('ukr', 'uk', 'українська мова', 'Ukrainian', 'ukrainien', NULL, NULL, NULL, NULL),
('umb', NULL, NULL, 'Umbundu', 'umbundu', NULL, NULL, NULL, NULL),
('und', NULL, NULL, 'Undetermined', 'indéterminée', NULL, NULL, NULL, NULL),
('urd', 'ur', 'اردو', 'Urdu', 'ourdou', NULL, NULL, NULL, NULL),
('uzb', 'uz', 'O‘zbek, Ўзбек, أۇزبېك‎', 'Uzbek', 'ouszbek', NULL, NULL, NULL, NULL),
('vai', NULL, NULL, 'Vai', 'vaï', NULL, NULL, NULL, NULL),
('ven', 've', 'Tshivenḓa', 'Venda', 'venda', NULL, NULL, NULL, NULL),
('vie', 'vi', 'Tiếng Việt', 'Vietnamese', 'vietnamien', NULL, NULL, NULL, NULL),
('vol', 'vo', 'Volapük', 'Volapük', 'volapük', NULL, NULL, NULL, NULL),
('vot', NULL, NULL, 'Votic', 'vote', NULL, NULL, NULL, NULL),
('wak', NULL, NULL, 'Wakashan languages', 'wakashanes, langues', NULL, NULL, NULL, NULL),
('wal', NULL, NULL, 'Wolaitta; Wolaytta', 'wolaitta; wolaytta', NULL, NULL, NULL, NULL),
('war', NULL, NULL, 'Waray', 'waray', NULL, NULL, NULL, NULL),
('was', NULL, NULL, 'Washo', 'washo', NULL, NULL, NULL, NULL),
('wel', 'cy', 'Cymraeg', 'Welsh', 'gallois', NULL, NULL, NULL, NULL),
('wen', NULL, NULL, 'Sorbian languages', 'sorabes, langues', NULL, NULL, NULL, NULL),
('wln', 'wa', 'walon', 'Walloon', 'wallon', NULL, NULL, NULL, NULL),
('wol', 'wo', 'Wollof', 'Wolof', 'wolof', NULL, NULL, NULL, NULL),
('xal', NULL, NULL, 'Kalmyk; Oirat', 'kalmouk; oïrat', NULL, NULL, NULL, NULL),
('xho', 'xh', 'isiXhosa', 'Xhosa', 'xhosa', NULL, NULL, NULL, NULL),
('yao', NULL, NULL, 'Yao', 'yao', NULL, NULL, NULL, NULL),
('yap', NULL, NULL, 'Yapese', 'yapois', NULL, NULL, NULL, NULL),
('yid', 'yi', 'ייִדיש', 'Yiddish', 'yiddish', NULL, NULL, NULL, NULL),
('yor', 'yo', 'Yorùbá', 'Yoruba', 'yoruba', NULL, NULL, NULL, NULL),
('ypk', NULL, NULL, 'Yupik languages', 'yupik, langues', NULL, NULL, NULL, NULL),
('zap', NULL, NULL, 'Zapotec', 'zapotèque', NULL, NULL, NULL, NULL),
('zbl', NULL, NULL, 'Blissymbols; Blissymbolics; Bliss', 'symboles Bliss; Bliss', NULL, NULL, NULL, NULL),
('zen', NULL, NULL, 'Zenaga', 'zenaga', NULL, NULL, NULL, NULL),
('zha', 'za', 'Saɯ cueŋƅ, Saw cuengh', 'Zhuang; Chuang', 'zhuang; chuang', NULL, NULL, NULL, NULL),
('znd', NULL, NULL, 'Zande languages', 'zandé, langues', NULL, NULL, NULL, NULL),
('zul', 'zu', 'isiZulu', 'Zulu', 'zoulou', NULL, NULL, NULL, NULL),
('zun', NULL, NULL, 'Zuni', 'zuni', NULL, NULL, NULL, NULL),
('zxx', NULL, NULL, 'No linguistic content; Not applicable', 'pas de contenu linguistique; non applicable', NULL, NULL, NULL, NULL),
('zza', NULL, NULL, 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'zaza; dimili; dimli; kirdki; kirmanjki; zazaki', NULL, NULL, NULL, NULL);
